#! python 3

import datetime as dt
import pandas as pd
import praw

def get_date(created):
    return dt.datetime.fromtimestamp(created)

reddit = praw.Reddit(client_id = 'ZWqh3Vq6QFGouQ', \
                     client_secret= 'yd2mu-7ZG9TvjJVoxT9giOvB4yE', \
                     user_agent= 'Goin Phisin', \
                     username= 'hippybongstocking', \
                     password='greenlantern95')

subreddit = reddit.subreddit('Phish')
sub1 = reddit.subreddit('phishcodes')

topics_dict = { "title":[], \
                "score":[], \
                "id":[], \
                "num_comments":[], \
                "created":[], \
                "selftext":[]}


for submission in subreddit.new(limit =5):
    topics_dict["title"].append(submission.title)
    topics_dict["score"].append(submission.score)
    topics_dict["id"].append(submission.id)
    topics_dict["num_comments"].append(submission.num_comments)
    topics_dict["selftext"].append(submission.selftext)

topics_data = pd.DataFrame(topics_dict)
topics_data
_timestamp = topics_data["created"].apply(get_date)
topics_data = topics_data.assign(timestamp = _timestamp)

#for submission in sub1.new(limit =5):
    #print ("FROM R\PHISHCODE")
    #print(submission.title, submission.created_utc)
    #print("\n")

